### ISSUE TITLE
Syntax error in ZTEST_RTTI

### ISSUE THREAD

**Issue by christianguenter2** [alaible/dbg_value_statement#1]
![grafik](https://user-images.githubusercontent.com/17437789/149077013-c47cf11e-254d-4152-984f-a9154af520fd.png)

**Comment by alaible** [comment]
Hallo Christian,
danke für deine Nachricht!
In dem Programm war noch eine Referenz auf eine globale Testklasse. Habe sie soeben entfernt :)
Gruß Alex

**Comment by alaible** [comment]
658e2d683c837ef8b35c980337424f4d5cff5c1d
